### ISSUE TITLE
Use of gorp makes testing really difficult

### ISSUE THREAD

**Issue by wchrisjohnson** [antonlindstrom/pgstore#21]
Great package, thanks very much for your efforts!

We have an app that is using this pkg, and have found writing tests to be really difficult due to the dependence on gorp. Why was this approach chosen vs just interacting with Postgres directly? How do users of this pkg in their apps do unit testing?

**Comment by antonlindstrom** [comment]
Sorry for the late response! Currently I haven't done that much of the unit testing without a database backing it up. I saw the PR, awesome effort to remove Gorp, thank you!

**Comment by wchrisjohnson** [comment]
Thanks!

If I finish up the PR, are you interested in merging it?

**Comment by antonlindstrom** [comment]
Yeah, as long as it's no breaking changes from the gorp implementation I'm totally up for removing the dependency. Thank you!

**Comment by wchrisjohnson** [comment]
Fantastic! We are trying to get a software release out the door so I'd like to get this finished up ASAP. I'll update the PR shortly.

Thank you!

**Comment by wchrisjohnson** [comment]
https://github.com/antonlindstrom/pgstore/pull/22 has now been updated and is basically passing all the unit tests. The Travis config for Go 1.5 looks to be the only issue with getting all green.

@antonlindstrom

**Comment by wchrisjohnson** [comment]
Thanks for merging, @antonlindstrom !!!
