### ISSUE TITLE
Create an initial release

### ISSUE THREAD

**Issue by janekolszak** [antonlindstrom/pgstore#27]
Hi!
Great package, thank you for writing this!

Please create an initial release something like 1.0.0.
This way we can manage dependencies via godeps or glide.

Thank you!

**Comment by antonlindstrom** [comment]
Hi!

I'm not familiar with how those tools work, are they referencing git tags? Would it suffice making a git tag?

Thanks!

**Comment by dgellow** [comment]
@antonlindstrom Yes, a git tag is enough :) 
As an addition, once you have a git tag you can also create a release on Github: https://github.com/antonlindstrom/pgstore/releases

**Comment by antonlindstrom** [comment]
1.0.0 tag is created :tada: It can be viewed on the releases page as well.

Thanks!

**Comment by dgellow** [comment]
Cool, thank you @antonlindstrom :)
