### ISSUE TITLE
support for different driver such as cloudsql postgres

### ISSUE THREAD

**Issue by ScaryWolfMan** [antonlindstrom/pgstore#29]
I am wondering if it would be possible to add support for additional drivers such as `"github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/dialers/postgres"`

It would be nice to have a way to pass the driver to https://github.com/antonlindstrom/pgstore/blob/master/pgstore.go#L40

In my app I load based on env flags, so dev would hit local database, but prod for example would use cloudpostgres.

Thanks

**Comment by antonlindstrom** [comment]
Hi! I think that should be possible as of existing code. If you implement the code in `NewPGStore` yourself and then pass the resulting `sql.DB` to [`NewPGStoreFromPool`](https://www.godoc.org/github.com/antonlindstrom/pgstore#NewPGStoreFromPool), it should hopefully work as intended.

Let me know if you run into any trouble with this and I will try to help (or make the necessary changes to make it work).

Cheers!

**Comment by ScaryWolfMan** [comment]
@antonlindstrom awesome!  That works!  Thank you so much for helping me with this issue, and thanks for making/maintaining this really cool project.

**Comment by antonlindstrom** [comment]
@ScaryWolfMan I'm glad I could help! Cheers! :+1:
