### ISSUE TITLE
Session Cleanup

### ISSUE THREAD

**Issue by elithrar** [antonlindstrom/pgstore#5]
From what I can determine, old sessions that have expired but have not been explicitly deleted will remain in the database.

Although this is not a huge problem unto itself, it's a little messy. The [boltstore](https://github.com/yosssi/boltstore) package has [a reaper function](https://github.com/yosssi/boltstore/blob/master/reaper/reaper.go) that operates via a goroutine and a `time.Ticker` to check the database for old sessions - 

e.g. 
```sql
DELETE FROM http_sessions WHERE expires_on > current_time
```

I figured I'd raise this issue before submitting a PR (super busy right now!) in the event you can get to a patch before I can.

**Comment by antonlindstrom** [comment]
@elithrar Thanks for bringing this up. There's currently no reaper process involved that's cleaning up old sessions.

If you're able to send a PR that would be awesome, otherwise I'll take a look in a few weeks.

Thanks!
